### ISSUE TITLE
login

### ISSUE THREAD

**Issue by DiegogGlez98** [DiegogGlez98/GonzalezHerrera_parcial_2#1]
Desarrollar un login(programacion libre).

**Comment by DiegogGlez98** [comment]
login terminado @ingreyeslara

**Comment by ingreyeslara** [comment]
![fallo](https://github.com/DiegogGlez98/GonzalezHerrera_parcial_2/assets/75334788/39e8d492-bd91-4a20-92d2-331e9bc55de1)
no se pudo acceder

**Comment by DiegogGlez98** [comment]
ya lo probe y a mi si me deja con estas credenciales

ingreyeslara
utd_2024

**Comment by ingreyeslara** [comment]
ya encontramos el error, la primera "u", es mayuscula, hay que hacer el cambio

**Comment by DiegogGlez98** [comment]
> ya encontramos el error, la primera "u", es mayuscula, hay que hacer el cambio

Actualizacion de credenciales corregidas,espero confirmacion

**Comment by ingreyeslara** [comment]
CORRECTO, LIBERADO!!!!!
